### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by Me1st3r** [BishopFox/unredacter#14]
Hi, I'm new to coding so I don't know how to npm install/start. I have searched on the internet for solutions but I can't understand all of them, so can you guys tell me how to install and use this tool? Also, I will need to unpixelized some pictures so can you explain how to do it with this tool?
Thanks a lot in advance! :)

**Comment by royarisse** [comment]
`npm` is a command that's part of node.js. You'd run it from your terminal (if you're using Linux) or from your command prompt (aka `cmd` if you're using Windows). The `npm` command is not available by default, you need to install that manually. The steps in simple form:

1. Download and install nodejs: https://nodejs.org/en/download/
2. Download this repository as a zip: https://github.com/BishopFox/unredacter/archive/refs/heads/main.zip and unzip.
3. Open your terminal on Linux or cmd on Windows and change directory to where you unzipped the repository.
4. There you type `npm install` and `npm start` to install and start the app respectively.

Hope this helps. Otherwise Google "install npm on Windows" or something for more details.

**Comment by Me1st3r** [comment]
Thanks a lot, but can you show me how to change the directory within the cmd? I'm currently using Windows.

**Comment by royarisse** [comment]
In Windows, use the `cd` command in `cmd`. For example, if you extracted the zip to `C:\Users\Me1st3r\Desktop\unredacter` you can type `cd C:\Users\Me1st3r\Desktop\unredactor`, then press `<enter>`.

An alternative — though I'm not sure it'll work in Windows 10/11 — is navigating to the folder using Explorer, then typing `cmd` in the addressbar and press `<enter>`. This should open command prompt in the current directory.

Good luck!|

Edit: I see you can drag the target directory into cmd as well, see: 
https://www.howtogeek.com/659411/how-to-change-directories-in-command-prompt-on-windows-10/

**Comment by kackebaellchen** [comment]
Works great .... have a lot of ideas with it ... Bugs are normaly for 1.0 ... i will work on it in future to make it great .... thx thx thx
